# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jdenis <jdenis@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/10 21:05:04 by dlacuey           #+#    #+#              #
#    Updated: 2024/07/17 00:52:29 by dlacuey          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CXX = c++

CXXFLAGS = -Wall -Wextra -Werror -std=c++98 -g

OBJS =																		\
																			\
					main.o													\
					bureaucrat.o											\
					aform.o													\
					shrubbery_creation_form.o								\
					robotomy_request_form.o									\
					presidential_pardon_form.o								\
					intern.o								\
																			\

NAME = at_least_this_beat_coffee_making

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) -o $(NAME) $^ $(LDFLAGS)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
